/* ═══════════════════════════════════════════════════════════════════════════
   PHONE REPORT — how broken each screen is on each phone, measured.

   REPORT-ONLY IN P0. Nothing here fails; it records the "before" state in
   e2e/reports/phone.json and phone.md so each later phase can show, per route
   and per width, what it fixed. When a phase makes a screen clean, that screen
   moves into the enforced list (E2E_ENFORCE) and from then on must stay clean.

   Widths are the common portrait phones, 320 (iPhone SE 1st gen, small
   Androids) to 430 (Pro Max).
   ═══════════════════════════════════════════════════════════════════════════ */
import { test, devices } from "@playwright/test";
import { writeFileSync, mkdirSync } from "node:fs";
import { bootStaff, bootCreator, staffRoutes, creatorRoutes, go, type Staff, type CreatorMode } from "./harness";
import { scanPhone, type PhoneScan } from "./measure";

const PHONES: Array<[number, number]> = [
  [320, 568], [360, 740], [375, 812], [390, 844], [393, 852], [414, 896], [430, 932],
];
const STAFF: Staff[] = ["admin", "team_lead", "coordinator", "employee"];
const CREATORS: CreatorMode[] = ["creator", "team_lead", "creator_admin"];

type Row = PhoneScan & { who: string; route: string; landed: string; width: number };
const rows: Row[] = [];

test.use({ ...devices["iPhone 13"], browserName: "chromium", deviceScaleFactor: 2 });

for (const [width, height] of PHONES) {
  test.describe(`${width}px`, () => {
    test.use({ viewport: { width, height } });

    for (const role of STAFF) {
      test(`staff ${role}`, async ({ page }) => {
        test.setTimeout(5 * 60_000);
        await bootStaff(page, role);
        for (const r of await staffRoutes(page)) {
          const landed = await go(page, r);
          rows.push({ who: role, route: r, landed, width, ...(await scanPhone(page)) });
        }
      });
    }
    for (const mode of CREATORS) {
      test(`creator ${mode}`, async ({ page }) => {
        test.setTimeout(3 * 60_000);
        await bootCreator(page, mode);
        for (const r of await creatorRoutes(page)) {
          const landed = await go(page, r);
          rows.push({ who: `creator:${mode}`, route: r, landed, width, ...(await scanPhone(page)) });
        }
      });
    }
  });
}

test.afterAll(() => {
  if (!rows.length) return;
  mkdirSync("e2e/reports", { recursive: true });
  rows.sort((a, b) => a.who.localeCompare(b.who) || a.route.localeCompare(b.route) || a.width - b.width);
  writeFileSync("e2e/reports/phone.json", JSON.stringify(rows, null, 1) + "\n");

  /* One line per who × route, worst width shown. */
  const key = (r: Row) => `${r.who} ${r.route}`;
  const groups = new Map<string, Row[]>();
  for (const r of rows) groups.set(key(r), [...(groups.get(key(r)) ?? []), r]);
  const broken = [...groups.values()].filter((g) => g.some((r) => r.offenders || r.contentOverflow));
  const at = (w: number) => rows.filter((r) => r.width === w);
  const lines = [
    "# Phone report", "",
    `Generated by \`npm run test:e2e -- phone-report\`. ${groups.size} role × route pairs at ${PHONES.length} widths.`, "",
    "| Width | Screens with overflow | Elements past the edge | Sub-44px tap targets |",
    "|---|---|---|---|",
    ...PHONES.map(([w]) => {
      const r = at(w);
      return `| ${w} | ${r.filter((x) => x.offenders || x.contentOverflow).length} of ${r.length} | ${r.reduce((n, x) => n + x.offenders, 0)} | ${r.reduce((n, x) => n + x.smallTaps, 0)} of ${r.reduce((n, x) => n + x.taps, 0)} |`;
    }),
    "", "## Screens that overflow (worst width)", "",
    "| Who | Route | Widths affected | Worst offender |", "|---|---|---|---|",
    ...broken.map((g) => {
      const worst = g.reduce((a, b) => ((b.worst[0]?.past ?? 0) > (a.worst[0]?.past ?? 0) ? b : a));
      const w = g.filter((r) => r.offenders || r.contentOverflow).map((r) => r.width).join(", ");
      return `| ${g[0].who} | \`${g[0].route}\` | ${w} | ${worst.worst[0] ? `\`${worst.worst[0].el}\` +${worst.worst[0].past}px` : `#content +${worst.contentOverflow}px`} |`;
    }),
  ];
  writeFileSync("e2e/reports/phone.md", lines.join("\n") + "\n");
});
